start_date: 2000-01-01
delta_threshold: 0.0001

cli:
  log_filename: /mnt/log/stockie/dev/stockie_cli.log
  log_level: INFO
  console: true

load_stock_prices:
  log_filename: /mnt/log/stockie/dev/load_stock_prices.log
  log_level: INFO
  console: false
  batch_size: 100
  processes: 1
  max_consecutive_batch_failures: 10

calculate_indicators: 
  profile: false
  calculate_processes: 8
  db_batch_size: 100
  log_filename: /mnt/log/stockie/dev/calculate_indicators.log
  log_level: INFO
  console: false

daily_job:
  load_stock_prices: true
  calculate_indicators: true
  log_filename: /mnt/log/stockie/dev/daily_job.log
  log_level: INFO
  console: true

vacuum:
  log_dir: /mnt/log/stockie/dev
  console: true
  file: true

db:
  host: localhost
  port: 5432
  dbname: stockie_dev_db
  user: stockie_dev
  admin_user: stockie_admin

tickers:
  benchmarks: ['SPY']
  cryptocurrencies: ['BTC-USD', 'ETH-USD', 'BNB-USD', 'SOL-USD', 'XRP-USD', 'ADA-USD', 'DOGE-USD', 'TRX-USD', 'AVAX-USD', 'LINK-USD', 'DOT-USD', 'LTC-USD', 'BCH-USD', 'ATOM-USD', 'XLM-USD']
  nyse: false
  nyse_american: false
  nyse_arca: false
  sp500: true
  nasdaq: false
  nasdaq100: false
  dow30: true
  russell2000: false

indicators:
  momentum:
    rsi:
      enabled: true
      window: 14
    stoch:
      enabled: true
      k_window: 14
      d_window: 3
    cci:
      enabled: true
      window: 20
    momentum:
      enabled: true
      window: 10

  performance:
    daily_returns:
      enabled: true
    cumulative_returns:
      enabled: true
    drawdown_duration:
      enabled: true

  risk:
    alpha:
      enabled: true
      benchmark: 'SPY'
      window: [63, 252]
      risk_free_benchmark: 0.04
    beta:
      enabled: true
      benchmark: 'SPY'
      window: [63, 252]
    rolling_volatility:
      enabled: true
      window: [21, 63]
    downside_deviation:
      enabled: true
      window: [21, 63]
      threshold: 0.0
    sharpe:
      enabled: true
      window: [21, 63]
      risk_free_rate: 0.04
    sortino:
      enabled: true
      window: [21, 63]
      target_return: 0.0
    max_drawdown:
      enabled: true
      window: 252
    calmar:
      enabled: true
      window: 252
  
  trend:
    sma:
      enabled: true
      window: [20, 50, 200]
    ema:
      enabled: true
      window: [20, 50, 200]
    macd:
      enabled: true
      fast_window: [12, 24]
      slow_window: [26, 52]
      signal_window: [9, 12]
    adx:
      enabled: true
      window: [14, 21]
 
  volatility:
    bollinger:
      enabled: true
      window: [21, 63]
      num_std: [2.0, 2.0]
    tr:
      enabled: true
    max_tr:
      enabled: true
      window: [21, 63]
    atr:
      enabled: true
      window: [21, 63]
    stddev:
      enabled: true
      window: [21, 63]

  volume:
    vsma:
      enabled: true
      window: [21, 63]
    vema:
      enabled: true
      window: [21, 63]
    pvt:
      enabled: true
    obv:
      enabled: true
    cmf:
      enabled: true
      window: [21, 63]
 